# Copyright (C) 2025-2025 Pico Technology Ltd. See LICENSE file for terms.
site_name: pyPicoSDK

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Reference:
    - Introduction: ref/introduction.md
    - PicoScope 6000E (ps6000a) Functions:
      - ref/ps6000a/init.md
      - ref/ps6000a/setup.md
      - ref/ps6000a/firmware.md
      - ref/ps6000a/channel.md
      - ref/ps6000a/digital.md
      - ref/ps6000a/trigger.md
      - ref/ps6000a/siggen.md
      - ref/ps6000a/buffers.md
      - ref/ps6000a/conversions.md
      - ref/ps6000a/captures.md
      - ref/ps6000a/run.md
      - ref/ps6000a/retrieval.md
    - PicoScope 3000E (psospa) Functions:
      - ref/psospa/init.md
      - ref/psospa/setup.md
      - ref/psospa/firmware.md
      - ref/psospa/channel.md
      - ref/psospa/digital.md
      - ref/psospa/trigger.md
      - ref/psospa/siggen.md
      - ref/psospa/buffers.md
      - ref/psospa/conversions.md
      - ref/psospa/captures.md
      - ref/psospa/run.md
      - ref/psospa/retrieval.md
      - ref/psospa/led.md
    - PicoScope 5000D (ps5000a) Functions:
      - ref/ps5000a/init.md
      - ref/ps5000a/setup.md
      - ref/ps5000a/channel.md
      - ref/ps5000a/trigger.md
      - ref/ps5000a/siggen.md
      - ref/ps5000a/buffers.md
      - ref/ps5000a/conversions.md
      - ref/ps5000a/captures.md
      - ref/ps5000a/run.md
      - ref/ps5000a/retrieval.md
      - ref/ps5000a/ets.md
    - ref/general.md
    - ref/constants.md
    - Config/Overrides: ref/configuration.md
  - Development:
    - Issues: dev/issues.md
    - Changelog: dev/changelog.md
    - Current Support: dev/current.md
    - Upcoming Roadmap: dev/roadmap.md

watch:
  - '../pypicosdk'

plugins:
- include-markdown
- search
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          allow_inspection: true
          docstring_style: google
          show_bases: true
          show_source: false
          inherited_members: true
          members_order: alphabetical
          separate_signature: false
          extensions:
          - griffe_inherited_docstrings

extra_css:
- css/mkdocstrings.css